CREATE TABLE user (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  street VARCHAR(150) NOT NULL,
  city VARCHAR(150) NOT NULL,
  zip_code VARCHAR(25) NOT NULL,
  country VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role ENUM('client', 'admin') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category (
 id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 name VARCHAR(45) NOT NULL
);

CREATE TABLE product (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  category_id INT NOT NULL
);

CREATE TABLE image (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  path TEXT(10000) NOT NULL,
  product_id INT NOT NULL,
  CONSTRAINT fk_image_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE cart (
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  PRIMARY KEY (user_id, product_id),
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE category_product (
  product_id INT NOT NULL,
  category_id INT NOT NULL,
  CONSTRAINT fk_category_product_product FOREIGN KEY (product_id) REFERENCES product (id),
  CONSTRAINT fk_category_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE favorite (
  user_id INT NOT NULL,
  product_id INT NOT  NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT fk_favorite_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE orders (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM ('en préparation', 'expédiée', 'livrée', 'annulée') NOT NULL,
  user_id INT NOT NULL,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE order_product (
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (order_id, product_id),
  CONSTRAINT fk_order_product_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_order_product_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE review (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  rating INT NOT NULL,
  comment TEXT NULL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES product (id)
);

INSERT INTO user (id, firstname, lastname, street, city, zip_code, country, email, phone, password, role)
VALUES 
(1, 'Jérôme', 'Doe', 'rue Lucien Faure', 'Bordeaux', '33300', 'France', 'innovprint3d@outlook.fr', '+33 612345678', '12345678', 'admin'),
(2, 'Cynthia', 'M', '1 rue Lucien Faure', 'Bordeaux', '33300', 'France', 'cm@outlook.fr', '+33 687654321', '87654321', 'client');

INSERT INTO category (id, name)
VALUES 
(1, "Figurines"),
(2, "Objets pratiques"),
(3, "Jeux");

INSERT INTO product (id, name, description, price, category_id)
VALUES
(1, "Doigt de lecture", "ma description", 2.00, 2),
(2, "Pot de fleur rond", "ma description", 6.00, 2),
(3, "Chat allongé", "ma description", 3.00, 1),
(4, "Chiot", "ma description", 3.00, 1),
(5, "Écureuil", "ma description", 3.00, 1),
(6, "Lapin", "ma description", 4.00, 1),
(7, "Lion", "ma description", 3.00, 1),
(8, "Panda", "Apportez une touche de douceur et de nature à votre décoration avec cette figurine de panda, imprimée en 3D en PLA de qualité. Conçue avec précision, cette pièce met en valeur les traits caractéristiques de l’animal emblématique, avec des finitions nettes et un rendu satiné qui valorisent chaque détail. Fabriquée à partir de PLA biosourcé, cette figurine allie légèreté, solidité et respect de l’environnement. Sa forme équilibrée et ses volumes bien définis en font un objet décoratif discret et élégant, idéal pour personnaliser un bureau, une étagère ou une vitrine. Cette pièce s’adresse autant aux amateurs de décoration contemporaine qu’aux passionnés d’animaux et de créations imprimées en 3D. Elle constitue également un cadeau original et responsable, à offrir en toute occasion.", 8.00, 1),
(9, "Pokeball Arcanin", "Découvrez cette superbe Pokéball Arcanin, imprimée en 3D avec précision à partir de PLA de haute qualité. Inspirée de l’univers Pokémon, cette pièce décorative met à l’honneur Arcanin, le Pokémon légendaire réputé pour sa prestance et sa puissance. Le design soigné de cette Pokéball associe des lignes nettes et des finitions impeccables, offrant un rendu fidèle et esthétique. Sa conception en PLA biosourcé garantit légèreté, solidité et respect de l’environnement, tout en apportant une finition satinée agréable au toucher et visuellement valorisante. Idéale pour les collectionneurs et les passionnés de la licence Pokémon, cette Pokéball peut être exposée sur une étagère, un bureau ou dans une vitrine dédiée. Elle constitue également une excellente idée cadeau pour les amateurs de culture geek et d’objets imprimés en 3D.", 11.00, 1),
(10, "Pokeball Ronflex", "Apportez une touche de nostalgie et de collection à votre intérieur avec cette Pokéball Ronflex imprimée en 3D en PLA de qualité. Fidèle à l’univers des célèbres jeux vidéo et séries animées, cette pièce décorative met à l’honneur Ronflex, le Pokémon emblématique reconnu pour sa force et son caractère paisible. Conçue avec soin, cette Pokéball présente des finitions nettes et des détails précis, faisant d’elle un objet à la fois décoratif et collector. Sa fabrication en PLA assure une impression légère, durable et respectueuse de l’environnement. La combinaison des couleurs caractéristiques et l’aspect satiné du matériau renforcent le réalisme et l’esthétique de cette pièce. Parfaite pour les amateurs de l’univers Pokémon, cette Pokéball trouvera naturellement sa place sur une étagère, un bureau ou dans une vitrine de collection. Elle peut également constituer une idée cadeau originale et personnalisée pour les passionnés de culture pop et d’impression 3D.", 11.00, 1),
(11, "Pot de fleur chien", "ma description", 7.00, 2),
(12, "Sifflet anti-agression", "Ce sifflet anti-agression imprimé en 3D en PLA bleu est un accessoire de sécurité pratique et indispensable à avoir à portée de main. Conçu pour être léger, compact et facile à transporter, il se glisse aisément dans une poche, un sac ou se fixe à un trousseau de clés grâce à son anneau porte-clés inclus. Sa fabrication en PLA, un matériau léger, résistant et respectueux de l’environnement, garantit à la fois robustesse et durabilité. Sa teinte bleu vif le rend facilement repérable en cas de besoin rapide. Ce sifflet a été pensé pour produire un son puissant et strident, capable d’attirer l’attention immédiate des personnes à proximité et de dissuader un agresseur potentiel. Idéal pour les joggeurs, les randonneurs, les étudiants ou toute personne souhaitant se sentir plus en sécurité au quotidien, ce sifflet peut également être utilisé dans le cadre d’activités sportives ou d’événements pour signaler une situation ou donner un signal sonore clair. Discret et esthétique, son design imprimé en 3D présente des finitions soignées et une ergonomie agréable, assurant une bonne prise en main. Un petit accessoire utile qui allie efficacité, simplicité et engagement pour des matériaux plus responsables.", 3.00, 2),
(13, "Étui brosse à dents", "ma description", 5.50, 2),
(14, "Chat", "ma description", 3.00, 1),
(15, "Chien", "ma description", 4.00, 1),
(16, "Support éponge maquillage", "ma description", 2.00, 2),
(17, "Cube infini", "ma description", 4.00, 3),
(18, "Dinosaure", "ma description", 4.00, 1),
(19, "Lapin qui dort", "ma description", 4.00, 1),
(20, "Lapin mignon", "ma description", 4.00, 1),
(21, "Licorne", "ma description", 4.00, 1),
(22, "Boîte de jeu morpion", "Redécouvrez le plaisir des jeux classiques avec ce jeu de morpion imprimé en 3D en PLA de qualité. Composé d’un plateau et de ses pions, cet ensemble offre une finition soignée et des lignes nettes pour un rendu esthétique et durable. Le plateau, structuré en cases parfaitement délimitées, permet de jouer facilement à deux, en intérieur comme en extérieur. Les pions, conçus en PLA biosourcé, assurent une bonne prise en main et une résistance à l’usage répété. Disponibles en deux coloris distincts pour chaque joueur, ils garantissent une lisibilité optimale pendant la partie. Léger et facile à transporter, ce jeu de morpion est idéal pour animer vos pauses, vos déplacements ou vos moments en famille. Sa conception en impression 3D lui confère un aspect moderne et personnalisable, s’intégrant aussi bien dans une salle de jeux que comme élément décoratif sur un bureau ou une table basse Parfait pour les amateurs de jeux traditionnels et d’objets imprimés en 3D, il constitue également une idée cadeau originale et conviviale.", 5.00, 3),
(23, "Oeuf décoration", "ma description", 5.00, 2),
(24, "Ouvre bouteille", "ma description", 2.00, 2),
(25, "Pancarte jardin", "Organisez facilement votre potager, vos jardinières ou votre balcon avec cet ensemble de pancartes de semis imprimées en 3D. Conçues en PLA de qualité et disponibles en plusieurs coloris, ces étiquettes décoratives et pratiques permettent d’identifier clairement vos plantations tout en apportant une touche colorée à vos espaces verts. Chaque pancarte est soigneusement réalisée avec une finition lisse et résistante, assurant une bonne tenue en extérieur comme en intérieur. Elles sont marquées du nom des différentes cultures — telles que Menthe, Carottes, Courgettes, Basilic, Persil ou encore Tomates — facilitant ainsi le repérage de vos semis et plantations au quotidien. Fabriquées en PLA biosourcé et respectueux de l’environnement, ces étiquettes jardin allient durabilité et esthétique. Leur format pratique permet de les planter directement dans la terre ou dans des pots, pour une organisation simple et élégante de vos cultures aromatiques, potagères ou florales. Parfaites pour les jardiniers amateurs ou confirmés, elles constituent également une idée cadeau originale et utile pour les passionnés de jardinage et de décoration naturelle.", 1.50, 2),
(26, "Pièces d'échecs", "Redécouvrez le jeu d’échecs avec ces pions imprimés en 3D en PLA de qualité. Chaque pièce est conçue avec précision pour respecter les formes traditionnelles du jeu, tout en bénéficiant d’une finition moderne et soignée. Fabriqués en PLA biosourcé et respectueux de l’environnement, ces pions allient légèreté et robustesse. Leur texture satinée et leur découpe nette assurent une excellente prise en main et un rendu esthétique valorisant sur tout type de plateau. Disponibles en plusieurs coloris sur demande, ces pions peuvent être utilisés pour compléter un jeu existant, personnaliser un échiquier ou constituer un élément décoratif original. Ils conviennent aussi bien à un usage de loisir qu’à des présentations ou animations autour du jeu d’échecs. Grâce à la qualité de leur impression et à la précision des détails, ces pions sont idéals pour les passionnés de jeux de stratégie et les amateurs d’objets imprimés en 3D.", 15.00, 3),
(27, "Porte cartes à jouer", "ma description", 5.00, 3),
(28, "Porte cartes de visite", "ma description", 6.00, 2),
(29, "Porte crayons rond", "ma description", 6.00, 2),
(30, "Pot de fleur", "ma description", 6.00, 2),
(31, "Petit pot de fleur", "Ajoutez une touche décorative discrète et soignée à votre intérieur avec ce petit pot de fleur imprimé en 3D en PLA. Conçu avec précision, ce modèle compact est idéal pour accueillir de petites plantes, des succulentes ou des boutures. Sa fabrication en PLA, un matériau biosourcé et respectueux de l’environnement, garantit un rendu à la fois léger et résistant, avec une finition satinée de qualité. Sa taille réduite en fait un accessoire parfait pour sublimer un coin de bureau, une étagère, un rebord de fenêtre ou même une table de chevet. Disponible en plusieurs coloris, ce petit pot de fleur se marie aisément avec des styles de décoration modernes, minimalistes ou naturels. Il constitue également un choix pratique et esthétique pour réaliser des compositions végétales en série ou pour offrir en cadeau.", 4.00, 2),
(32, "Poule", "Adoptez cette charmante poule, une pièce décorative originale imprimée en 3D avec précision à partir de PLA vert. Son design soigné et ses courbes douces en font un objet à la fois ludique et élégant, idéal pour personnaliser votre intérieur, une cuisine ou un bureau avec une touche de fantaisie. Grâce à l’impression 3D, chaque détail est minutieusement travaillé pour offrir un rendu homogène et de qualité. Fabriquée en PLA, un matériau biodégradable et respectueux de l’environnement, cette poule décorative associe esthétique et engagement écologique. Elle s’intégrera parfaitement dans une décoration moderne, rustique ou décalée et peut aussi constituer une idée de cadeau originale pour les amateurs de créations artisanales ou d’objets imprimés en 3D.", 3.00, 1),
(33, "Sapin décoratif", "Ajoutez une touche de modernité et d’élégance à votre intérieur avec cette pyramide décorative imprimée en 3D en PLA orangé. Sa silhouette géométrique aux lignes épurées et ses multiples facettes lui confèrent un aspect contemporain qui saura s’intégrer facilement dans différents styles de décoration, qu’ils soient modernes, minimalistes ou plus chaleureux. Imprimée en 3D avec précision, cette pièce offre des finitions soignées et une qualité de fabrication qui met en valeur le rendu du PLA, un matériau à la fois léger et résistant, connu pour son aspect lisse et satiné. Sa teinte orangée apporte une touche lumineuse et chaleureuse à vos espaces, qu’elle soit posée sur une étagère, une table basse ou un bureau.Polyvalente, cette pyramide peut être utilisée comme simple objet décoratif, comme presse-papiers ou comme élément de mise en scène pour vos photos et créations artistiques. Fabriquée à partir de PLA, un plastique biodégradable issu de ressources renouvelables, elle allie esthétique et démarche écoresponsable. Une idée de cadeau originale et design pour les amateurs de décoration contemporaine et d’objets imprimés en 3D.", 4.00, 2),
(34, "Support brosse à dents", "ma description", 6.50, 2),
(35, "Boîte rangement jeux Switch", "ma description", 5.00, 3),
(36, "Support écran", "Offrez à votre téléphone un support pratique et esthétique avec ce support de téléphone imprimé en 3D en PLA orange. Conçu pour allier simplicité, robustesse et design moderne, cet accessoire indispensable trouve facilement sa place sur un bureau, une table de chevet ou un plan de travail. Grâce à sa conception légère et stable, il permet de maintenir votre smartphone en position verticale ou inclinée selon vos besoins. Que ce soit pour regarder des vidéos, passer des appels en visioconférence, suivre une recette en cuisine ou consulter vos notifications sans avoir à tenir votre appareil en main, ce support vous assure un confort d’utilisation optimal. L’impression 3D de qualité garantit des finitions soignées et des lignes nettes, tandis que le PLA utilisé pour sa fabrication offre à la fois légèreté et solidité. Le coloris orange vif apporte une touche de couleur dynamique et contemporaine à votre espace de travail ou de détente. Compatible avec la majorité des modèles de téléphones, ce support est également facile à transporter et à ranger grâce à ses dimensions compactes. Fabriqué à partir de PLA, un matériau respectueux de l’environnement issu de ressources végétales renouvelables, il conjugue utilité quotidienne et engagement écologique. Idéal pour un usage personnel ou comme idée cadeau pratique et originale, ce support de téléphone imprimé en 3D séduit par sa simplicité, son efficacité et son design affirmé.", 7.00, 2),
(37, "Tirelire animal", "Apportez une touche de douceur et d’originalité à votre décoration intérieure avec ces adorables tirelires en forme d''ourson, entièrement imprimées en 3D. Conçues en PLA, un matériau écologique et résistant, ces tirelires séduisent par leur texture soignée qui imite l’aspect d’un tricot en laine, leur donnant un charme réconfortant et original. Ce duo se compose d’un petit chat bleu-violet aux traits minimalistes et attendrissants, et d’un charmant ourson crème aux oreilles rondes et à la truffe noire brillante. Chaque modèle présente des finitions impeccables et des détails soigneusement travaillés, comme les oreilles, les moustaches et les pattes, contribuant à leur aspect à la fois ludique et décoratif. La fente discrète située sur le dessus permet de glisser aisément pièces et billets, tandis qu’une ouverture astucieuse sous leur base permet de récupérer facilement le contenu sans abîmer l’objet. Ces tirelires sont idéales pour les chambres d’enfants, les bureaux, ou pour offrir un cadeau personnalisé et original à l’occasion d’un anniversaire ou d’une naissance. Fabriquées en impression 3D avec précision, elles sont légères, solides et respectueuses de l’environnement grâce à l’utilisation de PLA, un plastique biosourcé dérivé d’amidon de maïs. Un objet déco aussi pratique qu’attachant, à adopter sans hésiter !", 9.00, 2),
(38, "Tirelire cochon", "Ajoutez une touche d’humour et de tendresse à votre décoration grâce à cette adorable tirelire cochon, imprimée en 3D avec soin à partir de PLA rose pâle. Son design minimaliste et épuré séduit par ses lignes douces et arrondies, qui rappellent les jouets vintage tout en conservant une esthétique résolument contemporaine. Le petit museau blanc, les oreilles pointues et la queue en spirale discrètement gravée à l’arrière apportent une note ludique et charmante à cet objet décoratif. La fente, située sur le dessus de la tirelire, permet de glisser facilement pièces et billets, et une ouverture sous sa base offre un accès rapide et pratique à son contenu. Parfaite pour décorer une chambre d’enfant, un bureau ou offrir en cadeau à l’occasion d’une naissance ou d’un anniversaire, cette tirelire allie fonctionnalité et originalité. Fabriquée en PLA, un matériau biosourcé et respectueux de l’environnement, elle est à la fois légère et résistante, avec un aspect légèrement satiné dû à l’impression 3D qui lui confère un charme artisanal. Un objet aussi décoratif que pratique, qui ravira petits et grands collectionneurs de tirelires ou d’objets imprimés en 3D !", 9.00, 2),
(39, "Tirelire fusée", "Offrez une façon ludique et originale de mettre de l’argent de côté avec cette tirelire en forme de fusée, entièrement imprimée en 3D. Fabriquée en PLA de qualité, cette création se distingue par ses couleurs vives et sa finition soignée : une structure principale verte, des pieds et ailettes bleus, ainsi que des embouts de pieds jaunes, pour un ensemble joyeux et plein de caractère. Son design évoque une fusée rétro tout droit sortie d’un dessin animé ou d’un univers de science-fiction, avec ses formes arrondies, ses détails de rivets et ses pieds stabilisateurs. La fente située sur le haut permet d’insérer facilement pièces et billets. Idéale pour encourager petits et grands à économiser, cette tirelire décorative trouvera parfaitement sa place dans une chambre d’enfant, un bureau ou une étagère. L’impression 3D assure des finitions nettes et des détails précis. Fabriquée en PLA, un matériau biosourcé à base d’amidon de maïs, elle conjugue esthétique, robustesse et engagement écologique. Facile à ouvrir pour récupérer son contenu, elle combine aspect pratique et design original, et constitue une excellente idée cadeau pour les amateurs d’objets insolites, de décoration geek ou de pièces uniques imprimées en 3D.", 9.00, 2),
(40, "Tortue", "Apportez une touche naturelle et élégante à votre décoration avec cette tortue décorative imprimée en 3D en PLA vert. Conçue avec soin, cette pièce met en valeur les formes douces et équilibrées de la carapace et des pattes, offrant un rendu à la fois sobre et raffiné. Sa couleur verte satinée évoque la nature et la sérénité, ce qui en fait un choix idéal pour agrémenter un bureau, une étagère ou un espace de vie. La qualité de son impression 3D et la finesse des détails soulignent la modernité de cet objet décoratif, qui saura également trouver sa place dans un cadre professionnel ou commercial. Fabriquée en PLA, un matériau biosourcé et respectueux de l’environnement, cette tortue est à la fois légère, solide et durable. Elle constitue ainsi un objet de décoration original et responsable, adapté à différents styles d’intérieurs et ambiances.", 4.00, 1),
(41, "Toupie", "Découvrez cette toupie décorative imprimée en 3D en PLA bleu-violet, au design inspiré du volant d’un bateau. Sa forme élégante et symétrique évoque à la fois la précision mécanique et l’esthétique maritime, en faisant un objet original à exposer ou à utiliser en décoration. Conçue avec minutie, cette toupie offre un rendu soigné grâce à la qualité de son impression 3D et à la profondeur de sa teinte bleu-violet satinée. Son design circulaire et ajouré rappelle les gouvernails traditionnels des navires, apportant une note d’inspiration nautique à votre intérieur. Fabriquée en PLA, un matériau biosourcé à la fois solide et respectueux de l’environnement, cette pièce décorative s’intègre aussi bien dans un bureau, un salon ou un espace de travail. Elle peut également être proposée comme objet de collection ou élément de vitrine dans un cadre commercial ou événementiel.", 3.50, 3),
(42, "Vide poche", "ma description", 6.00, 2),
(43, "Support de manette jeux", "Mettez en valeur votre configuration de jeu avec ce support de manette unique, spécialement conçu pour allier fonctionnalité et esthétique. Imprimé en 3D avec soin à partir de PLA de qualité, ce support arbore une teinte rouge-orange saisissante qui attire instantanément le regard et apporte une touche dynamique à votre espace gaming. Son design original et travaillé présente une base aux lignes géométriques inspirées des structures cristallines, offrant à la fois stabilité et élégance. Sur cette base repose une manette stylisée, décorée de symboles de boutons et d’une illustration cartoon d’un primate malicieux, clin d’œil assumé aux univers vidéoludiques et à l’imaginaire rétro-gaming. Ce support est parfaitement adapté pour accueillir et exposer vos manettes lorsque vous ne les utilisez pas, évitant ainsi qu’elles traînent sur le bureau ou les étagères. Idéal pour maintenir l’ordre dans votre espace tout en valorisant vos accessoires de jeu, il s’intègre facilement dans une chambre, un salon ou un bureau grâce à son esthétique soignée et son rendu moderne. Fabriqué en PLA, un matériau léger, solide et respectueux de l’environnement issu de ressources renouvelables, ce support associe utilité et démarche responsable. Il constitue également un excellent cadeau pour les amateurs de jeux vidéo et les collectionneurs d’accessoires gaming originaux. Que ce soit pour sublimer votre installation ou offrir un présent original et pratique, ce support de manette imprimé en 3D répondra à toutes les attentes.", 7.00, 3),
(44, "Présentoir boucles d'oreilles hexagonal", "Mettez en avant vos boucles d’oreilles avec ce présentoir hexagonal au design moderne, imprimé en 3D avec précision à partir de PLA respectueux de l’environnement. Sa forme géométrique unique offre une présentation originale et élégante, permettant de disposer vos bijoux de manière ordonnée et esthétique. L’impression 3D garantit des finitions soignées et un rendu homogène, valorisant chaque détail du présentoir. Fabriqué en PLA biodégradable, ce support allie durabilité et engagement écologique. Adapté à un usage personnel, en boutique ou lors d’expositions, il s’intègre parfaitement dans tout type de décor et constitue une idée de cadeau distinguée pour les amateurs de bijoux et de créations artisanales.", 4.00, 2),
(45, "Présentoir boucles d'oreilles rond", "Exposez vos boucles d’oreilles avec élégance grâce à ce présentoir de forme ronde, imprimé en 3D avec précision à partir de PLA respectueux de l’environnement. Son design circulaire et épuré permet de présenter divers styles de boucles d’oreilles de façon ordonnée et esthétique. L’impression 3D garantit des finitions nettes et un rendu homogène, mettant en valeur chaque détail du présentoir. Fabriqué en PLA biodégradable, ce support allie durabilité et engagement écologique. Parfait pour un usage personnel, une boutique ou une exposition, il s’intègre harmonieusement dans tout type de décor et constitue une idée de cadeau raffinée pour les amateurs de bijoux ou d’objets imprimés en 3D.", 4.00, 2),
(46, "Présentoir colliers", "Mettez en valeur vos bijoux avec ce présentoir à colliers au design élégant, imprimé en 3D avec précision à partir de PLA écologique. Sa forme étudiée permet de disposer colliers, chaînes ou pendentifs de manière ordonnée, tout en les exposant avec raffinement. Grâce à l’impression 3D, les lignes sont nettes et les finitions soignées, offrant un rendu visuel harmonieux et professionnel. Fabriqué en PLA, un matériau biodégradable et respectueux de l’environnement, ce présentoir combine esthétique et démarche durable. Idéal pour une utilisation personnelle, en boutique ou lors d’expositions, il s’intègre facilement dans tout type de décoration et constitue également une idée de cadeau originale pour les amateurs de bijoux ou de créations artisanales.", 4.00, 2),
(47, "Support boule de noël", "ma description", 4.00, 2),
(48, "Support bouteille", "ma description", 6.00, 2),
(49, "Support verres sur bouteille", "ma description", 5.00, 2),
(50, "Support de Switch", "Optimisez votre espace de jeu avec ce support pour console Nintendo Switch, imprimé en 3D avec précision à partir de PLA de qualité. Conçu pour maintenir la console de manière stable et sécurisée, son design fonctionnel et soigné allie ergonomie et modernité. Grâce à l’impression 3D, chaque courbe et angle est travaillé avec minutie pour garantir un rendu homogène, durable et esthétique. Fabriqué en PLA, un matériau biodégradable et respectueux de l’environnement, ce support s’inscrit dans une démarche responsable tout en répondant aux exigences des joueurs. Parfait pour une installation propre et organisée, il convient aussi bien à un bureau, une étagère ou un meuble TV, et peut faire office de cadeau pratique pour les passionnés de jeux vidéo ou les amateurs d’accessoires imprimés en 3D.", 6.00, 2),
(51, "Pot à crayons oval", "Ajoutez une touche moderne et fonctionnelle à votre espace de travail avec ce pot à crayons ovale, imprimé en 3D avec précision à partir de PLA écologique. Son design épuré et ses lignes douces apportent une esthétique sobre et contemporaine, idéale pour organiser stylos, pinceaux ou accessoires de bureau. Grâce à l’impression 3D, chaque courbe est soigneusement définie pour un rendu homogène et de qualité. Fabriqué en PLA, un matériau biodégradable et respectueux de l’environnement, ce pot combine utilité et engagement durable. Il trouvera naturellement sa place sur un bureau, dans un atelier ou une chambre d’enfant, et constitue également une idée de cadeau utile et originale pour les amateurs d’objets design et responsables.", 5.00, 2),
(154, "Petit dinosaure", "Plongez dans l’univers fascinant de la préhistoire avec cette figurine de dinosaure, une pièce décorative imprimée en 3D avec précision à partir de PLA de qualité. Son design réaliste et ses lignes détaillées en font un objet aussi captivant qu’esthétique, parfait pour agrémenter une chambre, un bureau ou une bibliothèque. Grâce à la technologie d’impression 3D, chaque relief est fidèlement reproduit pour offrir un rendu homogène et soigneux. Conçue en PLA, un matériau biodégradable et respectueux de l’environnement, cette figurine allie durabilité et conscience écologique. Elle s’intégrera harmonieusement dans un intérieur contemporain, éducatif ou thématique, et constitue également une excellente idée de cadeau pour les passionnés de dinosaures, les enfants, les amateurs de modélisme ou de créations artisanales en impression 3D.", 3.00, 2);

INSERT INTO image (id, path, product_id)
VALUES 
(1, "../../public/img/products/bloque_page_1.jpg", 1),
(2, "../../public/img/products/pot_fleur_rond_1.jpg", 2),
(3, "../../public/img/products/chat_allonge_1.jpg", 3),
(4, "../../public/img/products/chiot_1.jpg", 4),
(5, "../../public/img/products/ecureuil_1.jpg", 5),
(6, "../../public/img/products/lapin_1.jpg", 6),
(7, "../../public/img/products/lion_1.jpg", 7),
(8, "../../public/img/products/panda_1.jpg", 8),
(9, "../../public/img/products/pokeball_arcanin_1.jpg", 9),
(10, "../../public/img/products/pokeball_ronflex_1.jpg", 10),
(11, "../../public/img/products/pot_fleur_chien_1.jpg", 11),
(12, "../../public/img/products/sifflet_1.jpg", 12),
(13, "../../public/img/products/boite_brosse_a_dents_1.jpg", 13),
(14, "../../public/img/products/chat_1.jpg", 14),
(15, "../../public/img/products/chien_flex_1.jpg", 15),
(16, "../../public/img/products/coquetier_1.jpg", 16),
(17, "../../public/img/products/cube_infini_1.jpg", 17),
(18, "../../public/img/products/dinosaure_1.jpg", 18),
(19, "../../public/img/products/lapin_yeux_fermes_1.jpg", 19),
(20, "../../public/img/products/lapin_yeux_ouverts_1.jpg", 20),
(21, "../../public/img/products/licorne_flex_1.jpg", 21),
(22, "../../public/img/products/morpion_1.jpg", 22),
(23, "../../public/img/products/oeuf_deco_1.jpg", 23),
(24, "../../public/img/products/ouvre_bouteille_1.jpg", 24),
(25, "../../public/img/products/pancarte_semis_1.jpg", 25),
(26, "../../public/img/products/pion_echec_1.jpg", 26),
(27, "../../public/img/products/porte_cartes_1.jpg", 27),
(28, "../../public/img/products/porte_cartes_visite_1.jpg", 28),
(29, "../../public/img/products/porte_crayons_rond_1.jpg", 29),
(30, "../../public/img/products/pot_fleur_pentagone_1.jpg", 30),
(31, "../../public/img/products/pot_fleur_petit_1.jpg", 31),
(32, "../../public/img/products/poule_flex_1.jpg", 32),
(33, "../../public/img/products/sapin_1.jpg", 33),
(34, "../../public/img/products/support_brosse_a_dents_1.jpg", 34),
(35, "../../public/img/products/support_cassette_switch_1.jpg", 35),
(36, "../../public/img/products/support_ecran_1.jpg", 36),
(37, "../../public/img/products/tirelire_animal_1.jpg", 37),
(38, "../../public/img/products/tirelire_cochon_1.jpg", 38),
(39, "../../public/img/products/tirelire_fusee_1.jpg", 39),
(40, "../../public/img/products/tortue_1.jpg", 40),
(41, "../../public/img/products/toupie_1.jpg", 41),
(42, "../../public/img/products/vide_poche_1.jpg", 42),
(43, "../../public/img/products/support_manette_1.jpg", 43),
(44, "../../public/img/products/presentoir_boucles_oreilles_hexagonal_1.jpg", 44),
(45, "../../public/img/products/presentoir_boucles_oreilles_rond_1.jpg", 45),
(46, "../../public/img/products/presentoir_colliers_1.jpg", 46),
(47, "../../public/img/products/support_boule_noel_1.jpg", 47),
(48, "../../public/img/products/support_bouteille_1.jpg", 48),
(49, "../../public/img/products/support_bouteille_verres_1.jpg", 49),
(50, "../../public/img/products/support_switch_1.jpg", 50),
(51, "../../public/img/products/pot_crayons_oval_1.jpg", 51),
(52, "../../public/img/products/bloque_page_2.jpg", 1),
(53, "../../public/img/products/bloque_page_3.jpg", 1),
(54, "../../public/img/products/pot_fleur_rond_2.jpg", 2),
(55, "../../public/img/products/pot_fleur_rond_3.jpg", 2),
(56, "../../public/img/products/chat_allonge_2.jpg", 3),
(57, "../../public/img/products/chat_allonge_3.jpg", 3),
(58, "../../public/img/products/chiot_2.jpg", 4),
(59, "../../public/img/products/chiot_3.jpg", 4),
(60, "../../public/img/products/ecureuil_2.jpg", 5),
(61, "../../public/img/products/ecureuil_3.jpg", 5),
(62, "../../public/img/products/lapin_2.jpg", 6),
(63, "../../public/img/products/lapin_3.jpg", 6),
(64, "../../public/img/products/lion_2.jpg", 7),
(65, "../../public/img/products/lion_3.jpg", 7),
(66, "../../public/img/products/panda_2.jpg", 8),
(67, "../../public/img/products/panda_3.jpg", 8),
(68, "../../public/img/products/pokeball_arcanin_2.jpg", 9),
(69, "../../public/img/products/pokeball_arcanin_3.jpg", 9),
(70, "../../public/img/products/pokeball_ronflex_2.jpg", 10),
(71, "../../public/img/products/pokeball_ronflex_3.jpg", 10),
(72, "../../public/img/products/pot_fleur_chien_2.jpg", 11),
(73, "../../public/img/products/pot_fleur_chien_3.jpg", 11),
(74, "../../public/img/products/sifflet_2.jpg", 12),
(75, "../../public/img/products/sifflet_3.jpg", 12),
(76, "../../public/img/products/boite_brosse_a_dents_2.jpg", 13),
(77, "../../public/img/products/boite_brosse_a_dents_3.jpg", 13),
(78, "../../public/img/products/chat_2.jpg", 14),
(79, "../../public/img/products/chat_3.jpg", 14),
(80, "../../public/img/products/chien_flex_2.jpg", 15),
(81, "../../public/img/products/chien_flex_3.jpg", 15),
(82, "../../public/img/products/coquetier_2.jpg", 16),
(83, "../../public/img/products/coquetier_3.jpg", 16),
(84, "../../public/img/products/cube_infini_2.jpg", 17),
(85, "../../public/img/products/cube_infini_3.jpg", 17),
(86, "../../public/img/products/dinosaure_2.jpg", 18),
(87, "../../public/img/products/dinosaure_3.jpg", 18),
(88, "../../public/img/products/lapin_yeux_fermes_2.jpg", 19),
(89, "../../public/img/products/lapin_yeux_fermes_3.jpg", 19),
(90, "../../public/img/products/lapin_yeux_ouverts_2.jpg", 20),
(91, "../../public/img/products/lapin_yeux_ouverts_3.jpg", 20),
(92, "../../public/img/products/licorne_flex_2.jpg", 21),
(93, "../../public/img/products/licorne_flex_3.jpg", 21),
(94, "../../public/img/products/morpion_2.jpg", 22),
(95, "../../public/img/products/morpion_3.jpg", 22),
(96, "../../public/img/products/oeuf_deco_2.jpg", 23),
(97, "../../public/img/products/oeuf_deco_3.jpg", 23),
(98, "../../public/img/products/ouvre_bouteille_2.jpg", 24),
(99, "../../public/img/products/ouvre_bouteille_3.jpg", 24),
(100, "../../public/img/products/pancarte_semis_2.jpg", 25),
(101, "../../public/img/products/pancarte_semis_3.jpg", 25),
(102, "../../public/img/products/pion_echec_2.jpg", 26),
(103, "../../public/img/products/pion_echec_3.jpg", 26),
(104, "../../public/img/products/porte_cartes_2.jpg", 27),
(105, "../../public/img/products/porte_cartes_3.jpg", 27),
(106, "../../public/img/products/porte_cartes_visite_2.jpg", 28),
(107, "../../public/img/products/porte_cartes_visite_3.jpg", 28),
(108, "../../public/img/products/porte_crayons_rond_2.jpg", 29),
(109, "../../public/img/products/porte_crayons_rond_3.jpg", 29),
(110, "../../public/img/products/pot_fleur_pentagone_2.jpg", 30),
(111, "../../public/img/products/pot_fleur_pentagone_3.jpg", 30),
(112, "../../public/img/products/pot_fleur_petit_2.jpg", 31),
(113, "../../public/img/products/pot_fleur_petit_3.jpg", 31),
(114, "../../public/img/products/poule_flex_2.jpg", 32),
(115, "../../public/img/products/poule_flex_3.jpg", 32),
(116, "../../public/img/products/sapin_2.jpg", 33),
(117, "../../public/img/products/sapin_3.jpg", 33),
(118, "../../public/img/products/support_brosse_a_dents_2.jpg", 34),
(119, "../../public/img/products/support_brosse_a_dents_3.jpg", 34),
(120, "../../public/img/products/support_cassette_switch_2.jpg", 35),
(121, "../../public/img/products/support_cassette_switch_3.jpg", 35),
(122, "../../public/img/products/support_ecran_2.jpg", 36),
(123, "../../public/img/products/support_ecran_3.jpg", 36),
(124, "../../public/img/products/tirelire_animal_2.jpg", 37),
(125, "../../public/img/products/tirelire_animal_3.jpg", 37),
(126, "../../public/img/products/tirelire_cochon_2.jpg", 38),
(127, "../../public/img/products/tirelire_cochon_3.jpg", 38),
(128, "../../public/img/products/tirelire_fusee_2.jpg", 39),
(129, "../../public/img/products/tirelire_fusee_3.jpg", 39),
(130, "../../public/img/products/tortue_2.jpg", 40),
(131, "../../public/img/products/tortue_3.jpg", 40),
(132, "../../public/img/products/toupie_2.jpg", 41),
(133, "../../public/img/products/toupie_3.jpg", 41),
(134, "../../public/img/products/vide_poche_2.jpg", 42),
(135, "../../public/img/products/vide_poche_3.jpg", 42),
(136, "../../public/img/products/support_manette_2.jpg", 43),
(137, "../../public/img/products/support_manette_3.jpg", 43),
(138, "../../public/img/products/presentoir_boucles_oreilles_hexagonal_2.jpg", 44),
(139, "../../public/img/products/presentoir_boucles_oreilles_hexagonal_3.jpg", 44),
(140, "../../public/img/products/presentoir_boucles_oreilles_rond_2.jpg", 45),
(141, "../../public/img/products/presentoir_boucles_oreilles_rond_3.jpg", 45),
(142, "../../public/img/products/presentoir_colliers_2.jpg", 46),
(143, "../../public/img/products/presentoir_colliers_3.jpg", 46),
(144, "../../public/img/products/support_boule_noel_2.jpg", 47),
(145, "../../public/img/products/support_boule_noel_3.jpg", 47),
(146, "../../public/img/products/support_bouteille_2.jpg", 48),
(147, "../../public/img/products/support_bouteille_3.jpg", 48),
(148, "../../public/img/products/support_bouteille_verres_2.jpg", 49),
(149, "../../public/img/products/support_bouteille_verres_3.jpg", 49),
(150, "../../public/img/products/support_switch_2.jpg", 50),
(151, "../../public/img/products/support_switch_3.jpg", 50),
(152, "../../public/img/products/pot_crayons_oval_2.jpg", 51),
(153, "../../public/img/products/pot_crayons_oval_3.jpg", 51),
(154, "../../public/img/products/dinosaure_flex_1.jpg", 154),
(155, "../../public/img/products/dinosaure_flex_2.jpg", 154),
(156, "../../public/img/products/dinosaure_flex_3.jpg", 154);